[package]
name = "scd"
version = "0.1.0"
authors = ["kurenaif <antyobido@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.5"
termion = "1.5"
unicode-width = "0.1.5"
rand = "0.6"
failure = "0.1.5"
env_logger = "0.6.1"
log = "0.4.6"
log4rs = "0.8.3"
